title: Ensembel Learning
output:
  html_document


## Preprocessing Data

```{r echo=TRUE}
library(caret)
library(randomForest)
```

```{r echo=TRUE}
library(readr)
raw_data<- read_csv("Subs to be reload (1).csv")
raw_data
clean_data = na.omit(raw_data)
clean_data = raw_data[c("current_tier", "available_points", "vlr_attached_p3d",
                        "flag_arpu_90d", "flag_arpu_last_30d", "tenure_rgu",
                        "rgu_flag", "rld_30d", "rld_60d", "rld_90d", "rld_tot_30d",
                        "rld_tot_60d", "rld_tot_90d", "reload_p90d",
                        "tot_month_rld", "denom_30d", "denom_60d", "denom_90d",
                        "curr_balance", "active_pack", "status", "n_days",
                        "arpu_rld","rld_nm")]
head(clean_data)

clean_data$rld_nm = as.factor(clean_data$rld_nm)
clean_data$current_tier = as.factor(clean_data$current_tier)
clean_data$flag_arpu_90d = as.factor(clean_data$flag_arpu_90d)
clean_data$flag_arpu_last_30d = as.factor(clean_data$flag_arpu_last_30d)
clean_data$rgu_flag = as.factor(clean_data$rgu_flag)
clean_data$status = as.factor(clean_data$status)
```

```{r echo=TRUE}
str(clean_data)
summary(clean_data)
```

## Pembagian Data
```{r}
set.seed(1)
i_train = createDataPartition(y = clean_data$rld_nm, times = 1, p = 0.8, list = FALSE)

train_data = clean_data[i_train, ]
test_data = clean_data[-i_train, ]

trControl <- trainControl(method = "repeatedcv",number = 10,repeats = 1)
preProcess <- c("center","scale")

colnames(clean_data)

train_data = train_data[1:1000,c(1:6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)]
```
## Algoritma

# Tree Bagging
```{r echo=TRUE}
set.seed(1)
model_bagging = train(rld_nm ~ .,
                      method='treebag',
                      data = train_data,
                      metric='Accuracy',
                      preProcess = preProcess,
                      trControl=trControl)
confusionMatrix(predict(model_bagging, test_data[1:100,]),
               test_data$rld_nm[1:100])
```

# Bagging dengan Regresi Logistik
```{r echo=TRUE}
set.seed(1)
model_logitboost = train(rld_nm ~ .,
                         method='LogitBoost',
                         data = train_data,
                         metric='Accuracy',
                         preProcess = preProcess,
                         trControl=trControl)
confusionMatrix(predict(model_logitboost, test_data[1:100,]),
                test_data$rld_nm[1:100])
```

# Adaboost
```{r echo=TRUE}
set.seed(1)
model_adaboost = train(rld_nm ~ .,
                       method='adaboost',
                       data = train_data,
                       metric='Accuracy',
                       preProcess = preProcess,
                       trControl=trControl)
confusionMatrix(predict(model_adaboost, test_data[1:100,]),
                test_data$rld_nm[1:100])
```

# Random Forest
```{r echo=TRUE}
set.seed(1)
model_randomforest = randomForest(as.factor(rld_nm) ~ .,
                                  data= train_data,
                                  ntree = 100, mtry=3)

confusionMatrix(predict(model_randomforest, test_data[1:100,]),
                test_data$rld_nm[1:100])
importance(model_randomforest)
plot(importance(model_randomforest))
```

